CREATE OR REPLACE VIEW comp.company AS
SELECT
  NULLIF(RTRIM(s."conm"), '')::varchar(70) AS "conm",
  NULLIF(RTRIM(s."gvkey"), '')::varchar(7) AS "gvkey",
  NULLIF(RTRIM(s."add1"), '')::varchar(66) AS "add1",
  NULLIF(RTRIM(s."add2"), '')::varchar(66) AS "add2",
  NULLIF(RTRIM(s."add3"), '')::varchar(66) AS "add3",
  NULLIF(RTRIM(s."add4"), '')::varchar(66) AS "add4",
  NULLIF(RTRIM(s."addzip"), '')::varchar(21) AS "addzip",
  NULLIF(RTRIM(s."busdesc"), '')::varchar(2001) AS "busdesc",
  NULLIF(RTRIM(s."cik"), '')::varchar(11) AS "cik",
  NULLIF(RTRIM(s."city"), '')::varchar(101) AS "city",
  NULLIF(RTRIM(s."conml"), '')::varchar(101) AS "conml",
  NULLIF(RTRIM(s."costat"), '')::varchar(2) AS "costat",
  NULLIF(RTRIM(s."county"), '')::varchar(101) AS "county",
  NULLIF(RTRIM(s."dlrsn"), '')::varchar(9) AS "dlrsn",
  NULLIF(RTRIM(s."ein"), '')::varchar(11) AS "ein",
  NULLIF(RTRIM(s."fax"), '')::varchar(21) AS "fax",
  NULLIF(RTRIM(s."fic"), '')::varchar(4) AS "fic",
  s."fyrc"::int2 AS "fyrc",
  NULLIF(RTRIM(s."ggroup"), '')::varchar(5) AS "ggroup",
  NULLIF(RTRIM(s."gind"), '')::varchar(7) AS "gind",
  NULLIF(RTRIM(s."gsector"), '')::varchar(3) AS "gsector",
  NULLIF(RTRIM(s."gsubind"), '')::varchar(9) AS "gsubind",
  NULLIF(RTRIM(s."idbflag"), '')::varchar(2) AS "idbflag",
  NULLIF(RTRIM(s."incorp"), '')::varchar(9) AS "incorp",
  NULLIF(RTRIM(s."loc"), '')::varchar(4) AS "loc",
  NULLIF(RTRIM(s."naics"), '')::varchar(7) AS "naics",
  NULLIF(RTRIM(s."phone"), '')::varchar(21) AS "phone",
  NULLIF(RTRIM(s."prican"), '')::varchar(9) AS "prican",
  NULLIF(RTRIM(s."prirow"), '')::varchar(9) AS "prirow",
  NULLIF(RTRIM(s."priusa"), '')::varchar(9) AS "priusa",
  NULLIF(RTRIM(s."sic"), '')::varchar(5) AS "sic",
  s."spcindcd"::int4 AS "spcindcd",
  s."spcseccd"::int4 AS "spcseccd",
  NULLIF(RTRIM(s."spcsrc"), '')::varchar(4) AS "spcsrc",
  NULLIF(RTRIM(s."state"), '')::varchar(9) AS "state",
  s."stko"::int2 AS "stko",
  NULLIF(RTRIM(s."weburl"), '')::varchar(61) AS "weburl",
  s."dldte"::date AS "dldte",
  s."ipodate"::date AS "ipodate",
  NULL::float8 AS "curr_sp500_flag"
FROM public.company s WHERE s.gvkey IN (SELECT gvkey FROM comp._na_gvkeys);
